const ADD_NOTE = "ADD_NOTE";
const DELETE_NOTE = "DELETE_NOTE";
const CHANGE_NOTE = "CHANGE_NOTE";
const ADD_TAG = "ADD_TAG";
const ACTIVE_NOTE = "ACTIVE_NOTE";
const ACTIVE_TAG = "ACTIVE_TAG";

export { ADD_NOTE, DELETE_NOTE, CHANGE_NOTE, ADD_TAG, ACTIVE_NOTE, ACTIVE_TAG }